project:
  type: book
  output-dir: ../../_build/junger-level-magic
  
book:
  title: "JÃ¼nger Level Magic"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Preset_Management.qmd
    - Preset_Manager_Window.qmd
    - Specifications.qmd
    - Open_Sound_Control_(OSC).qmd
  appendices:
    - ../flux_processing_release_notes.qmd

format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex
